export const GET_USER = "GET_USER"; // GET GENERAL USER DETAILS FOR REVIEW
export const AUTH_USER = "AUTH_USER";
export const SELF = "SELF"; // PERSONAL DETAILS
export const CLEAR_USER = "CLEAR_USER"; // SIGN OUT
